name: dierama
services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        labels:
            glance.name: Cloudflared
            glance.icon: /assets/cloudflare.svg
        # tunnel token is set in patch

    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE="0 */3 * * *"
            - DISPLAY_TIMEZONE=America/New_York
        volumes:
            - /home/ixora/services/speedtest-tracker:/config:rw
        labels:
            glance.name: Speedtest Tracker
            glance.icon: /assets/speedtest-tracker.png

    glance:
        image: glanceapp/glance
        volumes:
            # loading configs outside of vcs for now
            - /home/ixora/services/glance/config:/app/config:ro
            - /home/ixora/services/glance/assets:/app/assets:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            glance.name: Glance

    open-webui:
        image: ghcr.io/open-webui/open-webui:latest
        restart: unless-stopped
        environment:
            - PORT=3000
        volumes:
            - /home/ixora/services/open-webui/data:/app/backend/data:rw
        labels:
            glance.name: Open WebUI
            glance.icon: /assets/open-webui.png

    vaultwarden:
        image: vaultwarden/server:latest
        restart: always
        environment:
            - SIGNUPS_ALLOWED=false  # change to true if want signups
        volumes:
            - /home/ixora/services/vaultwarden/vw-data:/data:rw
        labels:
            glance.name: Vaultwarden
            glance.icon: /assets/vaultwarden.svg

    minio-obsidian:
        image: minio/minio:latest
        restart: unless-stopped
        command: server /data --console-address ":9001"
        volumes:
            - /home/ixora/services/minio-obsidian/data:/data:rw
        labels:
            glance.name: Obsidian DB
            glance.icon: /assets/minio-obsidian.svg
