# Input compose file for compose2nix
services:
  ollama:
    image: ollama/ollama
    deploy:
        resources:
            reservations:
                devices:
                - driver: cdi
                  device_ids: [nvidia.com/gpu=all]
                  capabilities: [gpu]

    restart: unless-stopped
    volumes:
      - /home/ixora/intaa/ollama_models:/root/.ollama/models

  openedai-speech:
    image: ghcr.io/matatonic/openedai-speech
    restart: unless-stopped
    deploy:
        resources:
            reservations:
                devices:
                - driver: cdi
                  device_ids: [nvidia.com/gpu=all]
                  capabilities: [gpu]
    environment:
      - TTS_HOME=/home/ixora/intaa/openedai-speech/voices
      - HF_HOME=/home/ixora/intaa/openedai-speech/voices
    volumes:
      - /home/ixora/intaa/openedai-speech/voices:/app/voices
      - /home/ixora/intaa/openedai-speech/config:/app/config

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    depends_on: [ollama, openedai-speech]
    environment:
      - PORT=3000
      - OLLAMA_BASE_URL=http://ollama:11434
      - AUDIO_TTS_ENGINE=openai
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://openedai-speech:8000/v1
      - AUDIO_TTS_OPENAI_API_KEY=sk-111111111
    ports:
      - 3000:3000
    volumes:
      - /home/ixora/intaa/open-webui/data:/app/backend/data
