name: Flake Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/flake-check.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/flake-check.yml"

jobs:
  flake-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v5
      with:
        nixpkgs-keys: nixpkgs-stable,nixpkgs-unstable

    - name: Install Nix
      uses: cachix/install-nix-action@master
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Nix Flake Check
      run: nix flake check --print-build-logs
