name: dierama
services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        # tunnel token is set in patch
    open-webui:
        image: ghcr.io/open-webui/open-webui:latest
        restart: unless-stopped
        environment:
          - PORT=3000
        ports:
          - 3000:3000
        volumes:
          - /home/ixora/services/open-webui/data:/app/backend/data
