name: dierama
services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        # tunnel token is set in patch
    open-webui:
        image: ghcr.io/open-webui/open-webui:latest
        restart: unless-stopped
        environment:
          - PORT=3000
        volumes:
          - /home/ixora/services/open-webui/data:/app/backend/data
    vaultwarden:
        image: vaultwarden/server:latest
        restart: always
        environment:
            - SIGNUPS_ALLOWED=false  # change to true if want signups
        volumes:
          - /home/ixora/services/vaultwarden/vw-data:/data
